apiVersion: v1
kind: Service
metadata:
  labels:
    db: tmetrica
  name: db-tmetrica
spec:
  ports:
  - name: "tmetrica-service"
    port: 5006
    targetPort: 5432
    #nodePort: 31000
  selector:
    db: tmetrica
