apiVersion: v1
kind: Service
metadata:
  labels:
    app: tmetrica
  name: tmetrica
spec:
  type: LoadBalancer
  ports:
  - name: "tmetrica-service"
    port: 5005
    targetPort: 8080
    nodePort: 31000
  selector:
    app: tmetrica
